const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Behaviors.Rotate,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.Tilemap,
		C3.Plugins.AJAX,
		C3.Plugins.Touch,
		C3.Plugins.advert,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Json,
		C3.Plugins.Date,
		C3.Plugins.Timeline,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Behaviors.Physics,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.SetJSON,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.advert.Cnds.IsBannerLoaded,
		C3.Plugins.advert.Acts.CreateBanner,
		C3.Plugins.advert.Cnds.IsRewardedInterstitialLoaded,
		C3.Plugins.advert.Acts.CreateRewardedInterstitial,
		C3.Plugins.advert.Cnds.IsRewardedLoaded,
		C3.Plugins.advert.Acts.CreateRewarded,
		C3.Plugins.advert.Acts.ShowBanner,
		C3.Plugins.advert.Acts.ShowRewardedInterstitial,
		C3.Plugins.advert.Acts.ShowRewarded,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.PlatformInfo.Exps.SafeAreaInsetLeft,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Exps.LayerNumber,
		C3.Plugins.PlatformInfo.Exps.SafeAreaInsetTop,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.PlatformInfo.Exps.SafeAreaInsetRight,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Behaviors.Physics.Cnds.CompareAngularVelocity,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Behaviors.Physics.Acts.SetAwake,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Tilemap.Acts.EraseTileRange,
		C3.Plugins.Tilemap.Exps.PositionToTileX,
		C3.Plugins.Tilemap.Exps.PositionToTileY,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Behaviors.Physics.Acts.RemoveJoints,
		C3.Behaviors.Physics.Acts.Teleport,
		C3.Plugins.System.Acts.Signal,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Timeline.Cnds.OnTimelineFinishedByTags,
		C3.Plugins.Timeline.Acts.SetInstance,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Timeline.Cnds.OnTimelineStartedByTags,
		C3.Plugins.Particles.Exps.LayerNumber,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Particles.Acts.SetParticleAcc,
		C3.Plugins.Particles.Acts.SetGravity,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.int,
		C3.Plugins.advert.Cnds.OnRewardedCancelled,
		C3.Plugins.advert.Cnds.OnRewardedFailedToLoad,
		C3.Plugins.advert.Cnds.OnRewardedComplete,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Exps.LayerNumber,
		C3.Plugins.Arr.Cnds.CompareXYZ,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Sprite.Cnds.HasParent,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Arr.Exps.Width
	];
};
self.C3_JsPropNameTable = [
	{PLay_B: 0},
	{OpenSett_B: 0},
	{OpenDaily_B: 0},
	{OpenShop_B: 0},
	{Sprite5: 0},
	{Load_Background: 0},
	{Id: 0},
	{Background1: 0},
	{Load_Bg: 0},
	{Loader: 0},
	{Close_B: 0},
	{Home_B: 0},
	{Music_B: 0},
	{Popup: 0},
	{Sound_B: 0},
	{Popup_Bg: 0},
	{Diamond_Bg: 0},
	{Claim_B: 0},
	{Bonus_Item: 0},
	{Fade: 0},
	{Transition: 0},
	{Claim2x_B: 0},
	{Rotate: 0},
	{Claimed_Effect: 0},
	{Tween: 0},
	{Diamond_Icon: 0},
	{Accept_B: 0},
	{Shop_Background_Item: 0},
	{Background2: 0},
	{Background3: 0},
	{Background4: 0},
	{Background5: 0},
	{Background6: 0},
	{Shop_Equipment_Item: 0},
	{Shop_Diamond_Icon: 0},
	{Cancel_B: 0},
	{Shop_Diamond_Icon2: 0},
	{Close_succeedBuy_B: 0},
	{Claimed_Effect2: 0},
	{ShopItem: 0},
	{Notif: 0},
	{Next_B: 0},
	{Backhome_B: 0},
	{BannerAd_Detection: 0},
	{Amount: 0},
	{Need: 0},
	{GemAd_B: 0},
	{GemAd_B2: 0},
	{GemAd_B3: 0},
	{GemAd_B4: 0},
	{Pause_B: 0},
	{Retry_B: 0},
	{id: 0},
	{Screw: 0},
	{Sprite3: 0},
	{Empty: 0},
	{Hole: 0},
	{prevVelocityX: 0},
	{prevVelocityY: 0},
	{Impluse: 0},
	{Plank_Bottom1: 0},
	{PlankHole: 0},
	{Tag: 0},
	{Screw_Collision: 0},
	{Diamond: 0},
	{Drill_B: 0},
	{Hole_Collision: 0},
	{Plank_Top1: 0},
	{Plank_Top2: 0},
	{Plank_Bottom2: 0},
	{Complete_Game: 0},
	{Sine: 0},
	{Sine2: 0},
	{Confetti: 0},
	{Particles: 0},
	{Hole_Limit: 0},
	{Tilemap: 0},
	{Hand: 0},
	{PlankShadow: 0},
	{Screw_Collision2: 0},
	{AJAX: 0},
	{Touch: 0},
	{MobileAdvert: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{PlatformInfo: 0},
	{Arr_PlayerData: 0},
	{Audio: 0},
	{DateJson: 0},
	{Date: 0},
	{Arr_DailyBonus: 0},
	{Arr_Shop: 0},
	{TimelineController: 0},
	{PackId: 0},
	{SpriteFont: 0},
	{Text: 0},
	{All_Button_F: 0},
	{Background_F: 0},
	{Physics: 0},
	{Physics_F: 0},
	{Plank_F: 0},
	{Plank_Bottom: 0},
	{Plank_top: 0},
	{Diamond_Effect: 0},
	{ID_Diamond_Icon: 0},
	{Sound: 0},
	{Music: 0},
	{Sound_Volume: 0},
	{VarDate: 0},
	{TimeZone: 0},
	{AdMob_Banner: 0},
	{AdMob_Interstitial_Reward: 0},
	{AdMob_Reward: 0},
	{Background_Id: 0},
	{Item_Type: 0},
	{Item_Id: 0},
	{Item_Price: 0},
	{ScrewId: 0},
	{OverlapingCount: 0},
	{OverlapingCenter: 0},
	{Radius: 0},
	{dx: 0},
	{StartTimer: 0},
	{Timer: 0},
	{Tutor: 0},
	{ScrewLayer: 0},
	{FreeGems: 0},
	{PendingPack: 0},
	{Done1: 0},
	{Done2: 0},
	{Done3: 0},
	{Done4: 0},
	{Loop: 0},
	{Type: 0},
	{Count: 0},
	{Count2: 0},
	{DiamondPopup: 0},
	{Loop_i: 0}
];

self.InstanceType = {
	PLay_B: class extends self.ISpriteInstance {},
	OpenSett_B: class extends self.ISpriteInstance {},
	OpenDaily_B: class extends self.ISpriteInstance {},
	OpenShop_B: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Load_Background: class extends self.ITiledBackgroundInstance {},
	Background1: class extends self.ITiledBackgroundInstance {},
	Load_Bg: class extends self.ISpriteInstance {},
	Loader: class extends self.ITiledBackgroundInstance {},
	Close_B: class extends self.ISpriteInstance {},
	Home_B: class extends self.ISpriteInstance {},
	Music_B: class extends self.ISpriteInstance {},
	Popup: class extends self.ISpriteInstance {},
	Sound_B: class extends self.ISpriteInstance {},
	Popup_Bg: class extends self.ISpriteInstance {},
	Diamond_Bg: class extends self.ISpriteInstance {},
	Claim_B: class extends self.ISpriteInstance {},
	Bonus_Item: class extends self.ISpriteInstance {},
	Transition: class extends self.ISpriteInstance {},
	Claim2x_B: class extends self.ISpriteInstance {},
	Claimed_Effect: class extends self.ISpriteInstance {},
	Diamond_Icon: class extends self.ISpriteInstance {},
	Accept_B: class extends self.ISpriteInstance {},
	Shop_Background_Item: class extends self.ISpriteInstance {},
	Background2: class extends self.ITiledBackgroundInstance {},
	Background3: class extends self.ITiledBackgroundInstance {},
	Background4: class extends self.ITiledBackgroundInstance {},
	Background5: class extends self.ITiledBackgroundInstance {},
	Background6: class extends self.ITiledBackgroundInstance {},
	Shop_Equipment_Item: class extends self.ISpriteInstance {},
	Shop_Diamond_Icon: class extends self.ISpriteInstance {},
	Cancel_B: class extends self.ISpriteInstance {},
	Shop_Diamond_Icon2: class extends self.ISpriteInstance {},
	Close_succeedBuy_B: class extends self.ISpriteInstance {},
	Claimed_Effect2: class extends self.ISpriteInstance {},
	ShopItem: class extends self.ISpriteInstance {},
	Notif: class extends self.ISpriteInstance {},
	Next_B: class extends self.ISpriteInstance {},
	Backhome_B: class extends self.ISpriteInstance {},
	BannerAd_Detection: class extends self.ISpriteInstance {},
	GemAd_B: class extends self.ISpriteInstance {},
	GemAd_B2: class extends self.ISpriteInstance {},
	GemAd_B3: class extends self.ISpriteInstance {},
	GemAd_B4: class extends self.ISpriteInstance {},
	Pause_B: class extends self.ISpriteInstance {},
	Retry_B: class extends self.ISpriteInstance {},
	Screw: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Hole: class extends self.ISpriteInstance {},
	Plank_Bottom1: class extends self.ISpriteInstance {},
	PlankHole: class extends self.ISpriteInstance {},
	Screw_Collision: class extends self.ISpriteInstance {},
	Diamond: class extends self.ISpriteInstance {},
	Drill_B: class extends self.ISpriteInstance {},
	Hole_Collision: class extends self.ISpriteInstance {},
	Plank_Top1: class extends self.ISpriteInstance {},
	Plank_Top2: class extends self.ISpriteInstance {},
	Plank_Bottom2: class extends self.ISpriteInstance {},
	Complete_Game: class extends self.ISpriteInstance {},
	Confetti: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Hole_Limit: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Hand: class extends self.ISpriteInstance {},
	PlankShadow: class extends self.ISpriteInstance {},
	Screw_Collision2: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	MobileAdvert: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Arr_PlayerData: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	DateJson: class extends self.IJSONInstance {},
	Date: class extends self.IInstance {},
	Arr_DailyBonus: class extends self.IArrayInstance {},
	Arr_Shop: class extends self.IArrayInstance {},
	TimelineController: class extends self.IInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Text: class extends self.ITextInstance {},
	All_Button_F: class extends self.ISpriteInstance {},
	Background_F: class extends self.ITiledBackgroundInstance {},
	Physics_F: class extends self.ISpriteInstance {},
	Plank_F: class extends self.ISpriteInstance {},
	Plank_Bottom: class extends self.ISpriteInstance {},
	Plank_top: class extends self.ISpriteInstance {}
}